---
title: "plotly"
author: "Ziqing Wang"
date: "2022-10-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

## import and process data
```{r}
data("nyc_airbnb")
```

```{r}
nyc_airbnb = nyc_airbnb %>%
  mutate(rating = review_scores_location / 2) %>%
  select(borough = neighbourhood_group, neighbourhood, price, room_type, lat, long, rating) %>%
  filter(borough == "Manhattan", room_type == "Entire home/apt", price %in% 100:500) %>%
  drop_na(rating)

```

## scatter plot
```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: ", price)) %>%
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    type = "scatter", mode = "markers",
    alpha = 0.5, text = ~text_label
  )
```

## boxplot
```{r}
nyc_airbnb %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% # rearrange order of factor levels by price
  plot_ly(
    y = ~price, color = ~neighbourhood,
    type = "box"
  )
```

## bar plot
```{r}
nyc_airbnb %>%
  count(neighbourhood) %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood,
          type = "bar", colors = "viridis")
```

## ggplotly
```{r}
ggp_scatterplot = nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(ggp_scatterplot)
```
This is usually slower and less visually appealing than directly plotting in plot_ly. 




